name: tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load environment variables
      uses: falti/dotenv-action@v1.1.3
      with:
        path: .env.example
        log-variables: true
        export-variables: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install BATS
      run: |
        sudo apt-get update
        sudo apt-get install -y bats bats-assert bats-support

    - name: Build test image
      run: |
        env
        chmod +x scripts/run_build.sh
        scripts/run_build.sh

    - name: Run tests
      env:
        NAGIOSADMIN_PASSWORD: ${{ env.NAGIOSADMIN_PASSWORD }}
        NSCA_PASSWORD: ${{ env.NSCA_PASSWORD }}
      run: |
        env
        chmod +x scripts/run_tests.sh
        scripts/run_tests.sh